### ISSUE TITLE
[BUG] --unity  command crashes due to  "not found in filtered tokens"

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo#2780]
When running the command `sozo build --unity` the build process runs fine but the creation of the bindings for the unity game engine seem to error out

Although not 100% sure, I believe to reproduce this bug you would need a model with a generic type, in our case I believe TStats model can either be a i8 or u8   [Link to our repo and where i think the issue generates from](https://github.com/grugslair/blob-arena-contracts/blob/310254a710ae9090527ee249743c683651a326b7/src/models/attack.cairo#L3)

The bindings should generate full without any errors

Proof
`alexhalo@Legion:~/Work-Repos/blob-arena-contracts$ sozo build --unity
    Updating git repository https://github.com/dojoengine/dojo
   Compiling blob_arena v0.7.1 (/home/alexhalo/Work-Repos/blob-arena-contracts/Scarb.toml)
    Finished dev profile target(s) in 13 seconds
thread 'main' panicked at /home/runner/.cargo/git/checkouts/cainome-971a2d0b3a80c185/5c2616c/crates/parser/src/tokens/mod.rs:161:25:
Composite blob_arena::stats::TStats::<core::integer::u8> not found in filtered tokens
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

This error was was reproduced in 1.0.1   1.0.4    1.0.5  version of dojo
PS: the v0.7.1 in the naming you can ignore the project is based on dojo version 1.0.1

**Comment by alexhaloETH** [comment]
As an update, I changed the name as I have noticed this happens also for the typescript

Also I have tried 1.0.8 version and the problem still persists

**Comment by glihm** [comment]
Sorry for the delay on that, will have a look or @Larkooo.

**Comment by Cygnusfear** [comment]
Currently having an identical error with the following code:

```cairo
#[derive(Serde, Copy, Drop, Introspect, PartialEq, Debug)]
pub enum InspectableActions {
    set_visible,
    read_description,
}

// Inspectable component
#[derive(Clone, Drop, Serde, Introspect, Debug)]
#[dojo::model]
pub struct Inspectable {
    #[key]
    pub inst: felt252,
    pub is_inspectable: bool,
    // properties
    pub is_visible: bool,
    pub description: Array<ByteArray>,
    pub action_map: Array<ActionMap<InspectableActions>>,
}

#[derive(Clone, Drop, Serde, Introspect, Debug)]
pub struct ActionMap<T> {
    pub action: ByteArray,
    pub inst: felt252,
    pub action_fn: T,
}
```

```system
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cainome-parser-0.1.0/src/tokens/mod.rs:183:25:
Composite lore::components::inspectable::ActionMap::<lore::components::inspectable::InspectableActions> not found in filtered tokens
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
